runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: discordpogo.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
- name: enum
  version: latest
- name: pytz
  version: latest