POKEMON_NAMES = [
 'Bulbasaur',
 'Ivysaur',
 'Venusaur',
 'Charmander',
 'Charmeleon',
 'Charizard',
 'Squirtle',
 'Wartortle',
 'Blastoise',
 'Caterpie',
 'Metapod',
 'Butterfree',
 'Weedle',
 'Kakuna',
 'Beedrill',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Rattata',
 'Raticate',
 'Spearow',
 'Fearow',
 'Ekans',
 'Arbok',
 'Pikachu',
 'Raichu',
 'Sandshrew',
 'Sandslash',
 'Nidoran♀',
 'Nidorina',
 'Nidoqueen',
 'Nidoran♂',
 'Nidorino',
 'Nidoking',
 'Clefairy',
 'Clefable',
 'Vulpix',
 'Ninetales',
 'Jigglypuff',
 'Wigglytuff',
 'Zubat',
 'Golbat',
 'Oddish',
 'Gloom',
 'Vileplume',
 'Paras',
 'Parasect',
 'Venonat',
 'Venomoth',
 'Diglett',
 'Dugtrio',
 'Meowth',
 'Persian',
 'Psyduck',
 'Golduck',
 'Mankey',
 'Primeape',
 'Growlithe',
 'Arcanine',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Abra',
 'Kadabra',
 'Alakazam',
 'Machop',
 'Machoke',
 'Machamp',
 'Bellsprout',
 'Weepinbell',
 'Victreebel',
 'Tentacool',
 'Tentacruel',
 'Geodude',
 'Graveler',
 'Golem',
 'Ponyta',
 'Rapidash',
 'Slowpoke',
 'Slowbro',
 'Magnemite',
 'Magneton',
 "Farfetch'd",
 'Doduo',
 'Dodrio',
 'Seel',
 'Dewgong',
 'Grimer',
 'Muk',
 'Shellder',
 'Cloyster',
 'Gastly',
 'Haunter',
 'Gengar',
 'Onix',
 'Drowzee',
 'Hypno',
 'Krabby',
 'Kingler',
 'Voltorb',
 'Electrode',
 'Exeggcute',
 'Exeggutor',
 'Cubone',
 'Marowak',
 'Hitmonlee',
 'Hitmonchan',
 'Lickitung',
 'Koffing',
 'Weezing',
 'Rhyhorn',
 'Rhydon',
 'Chansey',
 'Tangela',
 'Kangaskhan',
 'Horsea',
 'Seadra',
 'Goldeen',
 'Seaking',
 'Staryu',
 'Starmie',
 'Mr. Mime',
 'Scyther',
 'Jynx',
 'Electabuzz',
 'Magmar',
 'Pinsir',
 'Tauros',
 'Magikarp',
 'Gyarados',
 'Lapras',
 'Ditto',
 'Eevee',
 'Vaporeon',
 'Jolteon',
 'Flareon',
 'Porygon',
 'Omanyte',
 'Omastar',
 'Kabuto',
 'Kabutops',
 'Aerodactyl',
 'Snorlax',
 'Articuno',
 'Zapdos',
 'Moltres',
 'Dratini',
 'Dragonair',
 'Dragonite',
 'Mewtwo',
 'Mew',
 'Chikorita',
 'Bayleef',
 'Meganium',
 'Cyndaquil',
 'Quilava',
 'Typhlosion',
 'Totodile',
 'Croconaw',
 'Feraligatr',
 'Sentret',
 'Furret',
 'Hoothoot',
 'Noctowl',
 'Ledyba',
 'Ledian',
 'Spinarak',
 'Ariados',
 'Crobat',
 'Chinchou',
 'Lanturn',
 'Pichu',
 'Cleffa',
 'Igglybuff',
 'Togepi',
 'Togetic',
 'Natu',
 'Xatu',
 'Mareep',
 'Flaaffy',
 'Ampharos',
 'Bellossom',
 'Marill',
 'Azumarill',
 'Sudowoodo',
 'Politoed',
 'Hoppip',
 'Skiploom',
 'Jumpluff',
 'Aipom',
 'Sunkern',
 'Sunflora',
 'Yanma',
 'Wooper',
 'Quagsire',
 'Espeon',
 'Umbreon',
 'Murkrow',
 'Slowking',
 'Misdreavus',
 'Unown',
 'Wobbuffet',
 'Girafarig',
 'Pineco',
 'Forretress',
 'Dunsparce',
 'Gligar',
 'Steelix',
 'Snubbull',
 'Granbull',
 'Qwilfish',
 'Scizor',
 'Shuckle',
 'Heracross',
 'Sneasel',
 'Teddiursa',
 'Ursaring',
 'Slugma',
 'Magcargo',
 'Swinub',
 'Piloswine',
 'Corsola',
 'Remoraid',
 'Octillery',
 'Delibird',
 'Mantine',
 'Skarmory',
 'Houndour',
 'Houndoom',
 'Kingdra',
 'Phanpy',
 'Donphan',
 'Porygon2',
 'Stantler',
 'Smeargle',
 'Tyrogue',
 'Hitmontop',
 'Smoochum',
 'Elekid',
 'Magby',
 'Miltank',
 'Blissey',
 'Raikou',
 'Entei',
 'Suicune',
 'Larvitar',
 'Pupitar',
 'Tyranitar',
 'Lugia',
 'Ho-Oh',
 'Celebi'
]
MOVE_NAMES = {
 '1': 'Thunder Shock',
 '10': 'Bite',
 '100': 'X Scissor',
 '101': 'Flame Charge',
 '102': 'Flame Burst',
 '103': 'Fire Blast',
 '104': 'Brine',
 '105': 'Water Pulse',
 '106': 'Scald',
 '107': 'Hydro Pump',
 '108': 'Psychic',
 '109': 'Psystrike',
 '11': 'Pound',
 '110': 'Ice Shard',
 '111': 'Icy Wind',
 '112': 'Frost Breath',
 '113': 'Absorb',
 '114': 'Giga Drain',
 '115': 'Fire Punch',
 '116': 'Solar Beam',
 '117': 'Leaf Blade',
 '118': 'Power Whip',
 '119': 'Splash',
 '12': 'Double Slap',
 '120': 'Acid',
 '121': 'Air Cutter',
 '122': 'Hurricane',
 '123': 'Brick Break',
 '124': 'Cut',
 '125': 'Swift',
 '126': 'Horn Attack',
 '127': 'Stomp',
 '128': 'Headbutt',
 '129': 'Hyper Fang',
 '13': 'Wrap',
 '130': 'Slam',
 '131': 'Body Slam',
 '132': 'Rest',
 '133': 'Struggle',
 '134': 'Scald Blastoise',
 '135': 'Hydro Pump Blastoise',
 '136': 'Wrap Green',
 '137': 'Wrap Pink',
 '14': 'Hyper Beam',
 '15': 'Lick',
 '16': 'Dark Pulse',
 '17': 'Smog',
 '18': 'Sludge',
 '19': 'Metal Claw',
 '2': 'Quick Attack',
 '20': 'Vice Grip',
 '200': 'Fury Cutter',
 '201': 'Bug Bite',
 '202': 'Bite',
 '203': 'Sucker Punch',
 '204': 'Dragon Breath',
 '205': 'Thunder Shock',
 '206': 'Spark',
 '207': 'Low Kick',
 '208': 'Karate Chop',
 '209': 'Ember',
 '21': 'Flame Wheel',
 '210': 'Wing Attack',
 '211': 'Peck',
 '212': 'Lick',
 '213': 'Shadow Claw',
 '214': 'Vine Whip',
 '215': 'Razor Leaf',
 '216': 'Mud Shot',
 '217': 'Ice Shard',
 '218': 'Frost Breath',
 '219': 'Quick Attack',
 '22': 'Megahorn',
 '220': 'Scratch',
 '221': 'Tackle',
 '222': 'Pound',
 '223': 'Cut',
 '224': 'Poison Jab',
 '225': 'Acid',
 '226': 'Psycho Cut',
 '227': 'Rock Throw',
 '228': 'Metal Claw',
 '229': 'Bullet Punch',
 '23': 'Wing Attack',
 '230': 'Water Gun',
 '231': 'Splash',
 '232': 'Water Gun',
 '233': 'Mud Slap',
 '234': 'Zen Headbutt',
 '235': 'Confusion',
 '236': 'Poison Sting',
 '237': 'Bubble',
 '238': 'Feint Attack',
 '239': 'Steel Wing',
 '24': 'Flamethrower',
 '240': 'Fire Fang',
 '241': 'Rock Smash',
 '242': 'Transform',
 '243': 'Counter',
 '244': 'Powder Snow',
 '245': 'Close Combat',
 '246': 'Dynamic Punch',
 '247': 'Focus Blast',
 '248': 'Aurora Beam',
 '249': 'Charge Beam',
 '25': 'Sucker Punch',
 '250': 'Volt Switch',
 '251': 'Wild Charge',
 '252': 'Zap Cannon',
 '253': 'Dragon Tail',
 '254': 'Avalanche',
 '255': 'Air Slash',
 '256': 'Brave Bird',
 '257': 'Sky Attack',
 '258': 'Sand Tomb',
 '259': 'Rock Blast',
 '26': 'Dig',
 '260': 'Infestation',
 '261': 'Struggle Bug',
 '262': 'Silver Wind',
 '263': 'Astonish',
 '264': 'Hex',
 '265': 'Night Shade',
 '266': 'Iron Tail',
 '267': 'Gyro Ball',
 '268': 'Heavy Slam',
 '269': 'Fire Spin',
 '27': 'Low Kick',
 '270': 'Overheat',
 '271': 'Bullet Seed',
 '272': 'Grass Knot',
 '273': 'Energy Ball',
 '274': 'Extrasensory',
 '275': 'Futuresight',
 '276': 'Mirror Coat',
 '277': 'Outrage',
 '278': 'Snarl',
 '279': 'Crunch',
 '28': 'Cross Chop',
 '280': 'Foul Play',
 '281': 'Hidden Power',
 '29': 'Psycho Cut',
 '3': 'Scratch',
 '30': 'Psybeam',
 '31': 'Earthquake',
 '32': 'Stone Edge',
 '33': 'Ice Punch',
 '34': 'Heart Stamp',
 '35': 'Discharge',
 '36': 'Flash Cannon',
 '37': 'Peck',
 '38': 'Drill Peck',
 '39': 'Ice Beam',
 '4': 'Ember',
 '40': 'Blizzard',
 '41': 'Air Slash',
 '42': 'Heat Wave',
 '43': 'Twineedle',
 '44': 'Poison Jab',
 '45': 'Aerial Ace',
 '46': 'Drill Run',
 '47': 'Petal Blizzard',
 '48': 'Mega Drain',
 '49': 'Bug Buzz',
 '5': 'Vine Whip',
 '50': 'Poison Fang',
 '51': 'Night Slash',
 '52': 'Slash',
 '53': 'Bubble Beam',
 '54': 'Submission',
 '55': 'Karate Chop',
 '56': 'Low Sweep',
 '57': 'Aqua Jet',
 '58': 'Aqua Tail',
 '59': 'Seed Bomb',
 '6': 'Tackle',
 '60': 'Psyshock',
 '61': 'Rock Throw',
 '62': 'Ancient Power',
 '63': 'Rock Tomb',
 '64': 'Rock Slide',
 '65': 'Power Gem',
 '66': 'Shadow Sneak',
 '67': 'Shadow Punch',
 '68': 'Shadow Claw',
 '69': 'Ominous Wind',
 '7': 'Razor Leaf',
 '70': 'Shadow Ball',
 '71': 'Bullet Punch',
 '72': 'Magnet Bomb',
 '73': 'Steel Wing',
 '74': 'Iron Head',
 '75': 'Parabolic Charge',
 '76': 'Spark',
 '77': 'Thunder Punch',
 '78': 'Thunder',
 '79': 'Thunderbolt',
 '8': 'Take Down',
 '80': 'Twister',
 '81': 'Dragon Breath',
 '82': 'Dragon Pulse',
 '83': 'Dragon Claw',
 '84': 'Disarming Voice',
 '85': 'Draining Kiss',
 '86': 'Dazzling Gleam',
 '87': 'Moonblast',
 '88': 'Play Rough',
 '89': 'Cross Poison',
 '9': 'Water Gun',
 '90': 'Sludge Bomb',
 '91': 'Sludge Wave',
 '92': 'Gunk Shot',
 '93': 'Mud Shot',
 '94': 'Bone Club',
 '95': 'Bulldoze',
 '96': 'Mud Bomb',
 '97': 'Fury Cutter',
 '98': 'Bug Bite',
 '99': 'Signal Beam'
}